name: Flutter CI

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
      
      - name: Disable analytics
        run: |
          flutter config --no-analytics
          dart --disable-analytics
      
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          flutter pub get
      
      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          flutter test
      
      - name: Check formatting
        run: |
          cd ${{ github.workspace }}
          flutter format --set-exit-if-changed .
      
      - name: Run static analysis
        run: |
          cd ${{ github.workspace }}
          flutter analyze
